export type TAnchor =
  'main'
  | 'our-mission'
  | 'fund-cooperation'
  | 'international-activities'
  | 'purpose-and-activities'
  | 'good-deeds'
  | 'details'
  | 'contacts'
  | 'legislative-bases'
  | 'geography-of-activity'
